# Generated by Django 3.2.15 on 2022-08-03 17:49

from django.db import migrations, models
import phonenumber_field.modelfields
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=128, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=128, null=True)),
                ('nickname', models.CharField(blank=True, max_length=128, null=True)),
                ('preferred_username', models.CharField(blank=True, max_length=128, null=True)),
                ('website', models.CharField(blank=True, max_length=128, null=True)),
                ('zoneinfo', timezone_field.fields.TimeZoneField(blank=True, choices_display='WITH_GMT_OFFSET', null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('email_verified', models.DateTimeField(blank=True, null=True)),
                ('phone_number_verified', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
